export const skillsArray = [
  {
    id: 1,
    title: "Frontend",
    text: [
      "HTML5",
      "CSS",
      "Tailwind",
      "SASS",
      "Bootstrap",
      "Javascript",
      "TypeScript",
      "React",
      "Next.js",
      "Redux",
      "Redux Toolkit",
      "Effector",
      "MobX",
    ],
    iconClass: "skills__ux",
  },
  {
    id: 2,
    title: "Backend",
    text: ["NodeJS", "ExpressJS", "NestJS", "JWT", "REST API", "Swagger"],
    iconClass: "skills__web",
  },
  {
    id: 3,
    title: "Databases",
    text: [
      "MongoDB",
      "MariaDB",
      "PostgreSQL",
      "SQLite",
      "Firebase",
      "Mongoose",
      "pgAdmin",
      "Sequelize",
    ],
    iconClass: "skills__front",
  },
];
