export const skillsArray = [
  {
    id: 1,
    title: "Веб-Разработка",
    text: [
      "HTML5",
      "CSS",
      "Tailwind",
      "SASS",
      "Bootstrap",
      "Javascript",
      "TypeScript",
      "React",
      "Next.js",
      "Redux",
      "Redux Toolkit",
      "Effector",
      "MobX",
    ],
    iconClass: "skills__ux",
  },
  {
    id: 2,
    title: "Backend-Разработка",
    text: ["NodeJS", "ExpressJS", "NestJS", "JWT", "REST API", "Swagger"],
    iconClass: "skills__web",
  },
  {
    id: 3,
    title: "Базы данных",
    text: [
      "MongoDB",
      "MariaDB",
      "PostgreSQL",
      "SQLite",
      "Firebase",
      "Mongoose",
      "pgAdmin",
      "Sequelize",
    ],
    iconClass: "skills__front",
  },
  {
    id: 4,
    title: "Алгоритмы и структуры",
    text: [
      "Знание основных алгоритмов (сортировка, поиск, динамическое программирование)",
      "структур данных (массивы, списки, деревья, графы, хеш-таблицы), их применение для решения различных задач",
    ],
    iconClass: "skills__seo",
  },
];
